---
title: "01 R语言导论"
date-modified: last-modified
date-format: iso
highlight-style: pygments
number-sections: true
format: 
  html:
    toc: true
    toc-depth: 3
    toc-location: left
    code-fold: show
editor: visual
execute:
  warning: false
  cache: false
theme:
  light: flatly
  dark: darkly
---

# 包的下载和安装

## 常用安装
```{r}
#| eval: false

# 安装包
install.packages("ggplot2")
# 加载包
library(ggplot2)
# 卸载包
remove.packages("ggplot2")
```

```{r}
#| eval: false
# 更新包
update.packages("openxlsx")
# 解除包的加载
detach("ggplot2")
# 显示R软件中已经安装了哪些包
.packages(all.available = TRUE)
```

## 其他下载方式
```{r}
#| eval: false
# 从Github下载
devtools::install_github("tidyverse/dplyr")
# 本地安装
install.packages("D:/dplyr.zip",repos = NUll,type = "source")
# 从BiocManage下载
BiocManager::install("openxlsx")
```

# 基础内容
## 查看帮助文档

```{r}
#| eval: false
# 查看函数的相关说明
?mean
help(mean)
# F1键
```


```{r}
#| eval: false
# 查阅包的功能简介
help(package="ggplot2")
# 根据某算法的名字或关键词，搜索哪个包能实现算法
RSiteSearch("network")
```

## 查看数据集
```{r}
#| eval: false
# 查看数据集的详细信息
?mtcars 
help(mtcars)
# 查看数据集的数据结构
str(mtcars)
# 查看数据集的数据类型
class(mtcars)
```

## 路径设置
```{r}
#| eval: false
# 获取当前路径
getwd()
# 设置当前路径
setwd("D:/R/test")
```


# 基本运算

## 赋值
```{r}
a <- 2
```


## 四则运算
```{r}
#| collapse: true
#| prompt: true
#| comment: ""
2+4
2-4
2*4
2/4
5%/%2 # 整除
5 %% 2 # 求余
```




# R的数据类型及其操作
## 向量
### 向量的创建
#### 用c函数创建向量
```{r}
# 创建一个数值型的向量
x <- c(1,2,3,4,5)
x

# 创建一个字符串型的向量
y <- c("Hello","World")
y

# 创建一个逻辑型的向量
z <- c(TRUE,FALSE,TRUE)
z
```

#### 创建向量的其他方法
```{r}
#| collapse: true
v1 <- 1:10
v1
v2 <- seq(1,10,2)
v2
v3 <- rep(c(1,3),times=5)
v3
```

### 向量的索引

| 位置  | 1   | 2   | 3   | 4   | 5   |
| --- | --- | --- | --- | --- | --- |
| 值   | 2   | 3   | 5   | 8   | 10  |
```{r}
a <- c(2,3,5,8,10)
a
```

```{r}
#| collapse: true
#| prompt: true
#| comment: ""
# 访问a向量中第2个元素
a[2]
# 访问a向量中第2，5个元素
a[c(2,5)]
```

```{r}
#| collapse: true
#| prompt: true
#| comment: ""
# 向a向量中添加一个值100
a[6] <- 100
# 向a向量第3个位置后面添加一个元素值为1000
append(a,1000,after = 3)
# 排除第6个元素
a[-6]
```


### 向量的基本计算
```{r}
#| collapse: true
#| prompt: true
#| comment: ""
a <- c(2,3,5,8,10)
# 计算均值
mean(a)
# 计算总和
sum(a)
```

