---
title: "05 分布数据可视化"
date-modified: last-modified
date-format: iso
highlight-style: pygments
number-sections: true
format: 
  html:
    toc: true
    toc-depth: 4
    toc-location: left
    toc-title: Contents
    code-fold: show
editor: visual
execute:
  warning: false
  cache: true
crossref: 
  fig-title: 图 #图的默认标签（默认是"Figure"）
  fig-prefix: 图 # 图的默认引用样式（默认是"Figure"）
theme:
  light: flatly
  dark: darkly
---

# 准备

## 准备包

```{r}
#| message: false
library(ggplot2) #绘图
library(dplyr) #数据分析
library(RColorBrewer) #调用调色板
```

## 主题设置

```{r}
#| message: false
library(ggplot2)
mytheme <-   theme(
    text = element_text(size = 16,
                        family = "STKaiti"),
    axis.title = element_text(size = 20)
  )
```

```{r}
#| include: false
library(showtext)
showtext_auto(enable=T)
font_add("STKaiti","/Library/Fonts/stkaiti.ttf")
```

## 准备数据
```{r}
data4_1 <- read.csv("../Input/classdata/mydata/chap04/data4_1.csv",stringsAsFactors = T)
```

# 直方图

## hist函数

```{r}
library(ggplot2)
str(diamonds)
```

钻石价格的分布
```{r}
hist(diamonds$price,xlab = "price",
     main = "直方图")
```

## ggplot2包的geom_histogram函数
```{r}
ggplot(diamonds,aes(x=price))+
  geom_histogram(bins = 30)
```

### 绘制基于空气质量指标AQI的直方图
```{r}
ggplot(data4_1,aes(x=AQI))+
  geom_histogram(bins = 15,
                 fill = "lightgreen",
                 color = "grey50")+
  xlim(0,300)
```

```{r}
ggplot(data4_1,aes(x=AQI))+
  geom_histogram(binwidth = 10,
                 fill = "lightgreen",
                 color = "grey50")
```

```{r}
library(gridExtra)
p1 <- ggplot(data4_1,aes(x=AQI))+
  geom_histogram(bins = 15,
                 fill = "lightgreen",
                 color = "grey50")+
  xlim(0,300)
p2 <- ggplot(data4_1,aes(x=AQI))+
  geom_histogram(binwidth = 10,
                 fill = "lightgreen",
                 color = "grey50")
grid.arrange(p1,p2,ncol=2)
```

### 为直方图添加信息

#### 添加相关信息

```{r}
p1 <- ggplot(data4_1,aes(x=AQI))+
  geom_histogram(fill="lightgreen",
                 color="grey50")
```

添加地毯图
```{r}
p1+geom_rug(size=0.2,color="blue3")
```

添加偏度系数
```{r}
paste0("偏度系数=",2)
```


```{r}
library(e1071)
a <- paste0("偏度系数=",round(skewness(data4_1$AQI),4))
```

```{r}
p1+
  annotate("text",x=265,y=37,
           label=a)
```

添加峰度系数
```{r}
peak <- round(kurtosis(data4_1$AQI),4)
b <- paste0("峰度系数=",peak)
```

```{r}
p1+annotate("text",x=265,y=37,
            label=b)
```

### 直方图y轴以核密度值的方式进行显示
```{r}
ggplot(data4_1,aes(x=AQI,y=after_stat(density)))+
  geom_histogram(fill="lightgreen",
                 color="grey50")+
  geom_density()
```

```{r}
ggplot(data4_1,aes(x=AQI,y=after_stat(density)))+
  geom_density()
```

```{r}
ggplot(diamonds,aes(x=price,y=after_stat(density)))+
  geom_histogram(color="grey50",
                 fill="lightgreen")+
  geom_density()
```

# 核密度图
```{r}
#| layout-ncol: 2
ggplot(data4_1,aes(x=AQI))+
  geom_density(bw=3,fill="lightblue",color="blue3")+
  labs(title = "(a) bw=3")

ggplot(data4_1,aes(x=AQI))+
  geom_density(bw=5,fill="lightblue",color="blue3")+
  labs(title = "(b) bw=5")

ggplot(data4_1,aes(x=AQI))+
  geom_density(bw=5,fill="lightblue",color="blue3")+
  labs(title = "(c) bw=10")
```
# 多参数比较
## 叠加直方图
```{r}
library(reshape2)
df <- melt(data4_1,
           id.vars = c("日期","质量等级"),
           variable.name = "空气指标",
           value.name = "指标值")
head(df)
```

```{r}
ggplot(df,aes(x=指标值,y=after_stat(density),fill = 空气指标))+
  geom_histogram(color="grey50",
                 alpha=0.6)
```

```{r}
library(dplyr)
df %>% filter(空气指标 %in% c("PM2.5","AQI")) %>% 
  ggplot(aes(x=指标值,y=after_stat(density),fill=空气指标))+
  geom_histogram(color="grey0",alpha=0.5)
```

## 核密度比较图

```{r}
ggplot(df,aes(x=指标值,fill=空气指标))+
  geom_density()
```

```{r}
library(dplyr)
df %>% filter(空气指标 %in% c("PM2.5","AQI")) %>% 
  ggplot(aes(x=指标值,fill=空气指标))+
  geom_density(alpha=0.6)
```




